name: dvc-cml
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./model-cicd-pipeline/dvc-cml-model-metric-tracking
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          dvc repro 

          git fetch --prune ## https://git-scm.com/docs/git-fetch
          dvc metrics diff --show-md dev > report.md

          echo "## Validating results by region"
          # cml-publish by_region.png --md >> report.md
          cml comment create report.md